### ISSUE TITLE
Problem grabbing?

### ISSUE THREAD

**Issue by conxr** [apierz/chunkbar.widget#1]
Which other packages are needed?
I have python but it looks like this when I install.

<img width="1440" alt="screen shot 2018-03-01 at 23 54 15" src="https://user-images.githubusercontent.com/31190088/36876302-403f83f8-1dac-11e8-9887-7b4ca8858891.png">

Also, should the git clone link read /apierz/nerdbar.widget/ or /apierz/chunkbar.widget/?

I've tried both & neither work for me

Thanks!

**Comment by apierz** [comment]
The readme should be /apierz/chunkbar.widget. I just transferred it over from the old version and forgot to change it so thanks for catching that for me. Chunkbar is for Chunkwm and Nerdbar is for KWM.

The python scripts use python 3 so that might be an issue.

Some people have problems with the scripts using relative paths, but I haven't been able to reproduce it to figure out what to fix. If you go into the individual coffee files and replace the` ./scripts/scriptname` path with an absolute path like `/Users/You/YourWidgetFolder/scripts/scriptname` that should fix things.

If anyone sees this and knows what I'm doing wrong with the relative paths, please let me know.

**Comment by conxr** [comment]
Thanks for the quick reply!

Yeah I thought it might of been python, but I am running 3.6, so I don't think it should be that.

Followed your instructions, putting them in the widget folder, my home folder, and also /usr/bin/local to see if it made any difference, but it keeps giving me the same error.

<img width="1440" alt="screen shot 2018-03-02 at 11 13 44" src="https://user-images.githubusercontent.com/31190088/36896501-dd77e0f8-1e0a-11e8-9b91-df2043135a43.png">

From the little text I can see, it looks to me as if the coffee files are still somehow searching for the ./scripts/ folder, how can this be?
